version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: gnivc_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gnivc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: gnivc_minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin #минимум 3 символа
      MINIO_ROOT_PASSWORD: password #минимум 8 символов
    volumes:
      - ./config/minio:/data